# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: frontend

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: /home/server/react_app

    steps:
    - uses: actions/checkout@v2
    - name: refresh from Github - standard branch is set to Development
      run: sudo git pull

    - uses: actions/checkout@v2
    - name: Take down allready running docker container
      run:  docker-compose -f docker-compose-dev.yml down

    - uses: actions/checkout@v2
    - name: docker compose with Dockerfile.dev and timestamp
      run:  docker-compose -f docker-compose-dev.yml up -d --build